name: Run install.sh

on:
  push:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make install.sh executable
        run: chmod +x ./install.sh

      - name: Run install.sh
        run: ./install.sh
