name: Verify AeNux Setup

on:
  workflow_dispatch:

jobs:
  verify-aenux:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install --install-recommends -y wget unzip wine64 wine32

      - name: Check Wine Installation
        run: |
          wine --version || (echo "Wine failed to install" && exit 1)

      - name: Setup AeNux Directory
        run: |
          mkdir -p $HOME/cutefishaep/AeNux
          echo "Test file" > $HOME/cutefishaep/AeNux/AfterFX.exe

      - name: Confirm AeNux Directory
        run: |
          if [[ -f "$HOME/cutefishaep/AeNux/AfterFX.exe" ]]; then
            echo "AeNux directory and executable OK."
          else
            echo "AeNux setup failed." && exit 1
          fi
